FROM appsody/nodejs:0.3
RUN npm i -g webpack webpack-cli jest
ENV APPSODY_PROJECT_DIR=/project
ENV APPSODY_MOUNTS=/:/project/user-app
ENV APPSODY_DEPS=/project/user-app/node_modules

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/node_modules
ENV APPSODY_WATCH_REGEX="^.*.ts$"

ENV APPSODY_PREP="npm install  --prefix user-app  && npm audit fix --prefix user-app && webpack-cli --prefix user-app"

ENV APPSODY_RUN="webpack-cli && npm start"
ENV APPSODY_RUN_ON_CHANGE="webpack-cli && npm start"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="npm run debug"
ENV APPSODY_DEBUG_ON_CHANGE="npm run debug"
ENV APPSODY_DEBUG_KILL=true


COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config
WORKDIR /project
RUN npm install && npm audit fix

ENV PORT=3000
ENV NODE_PATH=/project/user-app/node_modules

EXPOSE 3000
EXPOSE 9229