name: LoopBack 4
version: 0.1.0
description: LoopBack 4 API Framework for Node.js
maintainers:
  - name: Raymond Feng
    email: enjoyjava@gmail.com
    github-id: raymondfeng
default-template: scaffold
language: nodejs
license: Apache-2.0