name: Quarkus
version: 0.3.0
description: Quarkus runtime for running Java applications
license: Apache-2.0
language: java
maintainers:
  - name: Paul Robinson
    email: probinso@redhat.com
    github-id: paulrobinson
default-template: default
requirements:
   appsody-version: ">= 0.6.0"
