name: Spring Boot®
version: 0.3.6
description: Spring Boot using OpenJ9 and Maven
license: Apache-2.0
language: java
maintainers:
  - name: Erin Schnabel
    email: schnabel@us.ibm.com
    github-id: ebullient
default-template: default
