id: java-spring-boot2
name: Java application using Spring Boot 2
version: 0.2.1
description: Spring Boot 2 project with health and metrics actuators enabled. Metrics support is provided by Micrometer, and is configured with Prometheus support.
maintainer: Erin Schnabel <schnabel@us.ibm.com>
default-template: default
license: Apache-2.0