name: Spring Boot®
version: 0.3.24
description: Spring Boot using OpenJ9 and Maven
license: Apache-2.0
language: java
maintainers:
  - name: Erin Schnabel
    email: schnabel@us.ibm.com
    github-id: ebullient
  - name: Ozzy Osborne
    email: ozzy@ca.ibm.com
    github-id: bardweller
default-template: default
requirements:
   appsody-version: ">= 0.5.0"
   docker-version: ">= 17.09.0"
templating-data:
  baseimage: kabanero/ubi8-maven:0.3.0
  finalimage: adoptopenjdk/openjdk8-openj9:ubi-jre
  parentpomgroup: dev.appsody
  parentpomid: spring-boot2-stack
  parentpomrange: '[0.3, 0.4)'
  parentpomfilename: appsody-boot2-snowdrop-pom.xml
