# Dockerfile for building the stack

FROM registry.access.redhat.com/ubi7/ubi

# See https://appsody.dev/docs/stacks/environment-variables for more information about each variable.

# Mount the application directory into the container filesystem, for example
ENV APPSODY_MOUNTS=/:/project/userapp

# Define a volume for dependencies to be stored between runs, for example
ENV APPSODY_DEPS=/project/deps

# Directories to watch for changes in
ENV APPSODY_WATCH_DIR=/project/userapp

# Directories to ignore changes in
ENV APPSODY_WATCH_IGNORE_DIR= 

# Types of file that will trigger a re-launch (change this to be specific to your application).
ENV APPSODY_WATCH_REGEX="^.*.*"

# Optional command executed before RUN/TEST/DEBUG - typically used to install any dependencies from
# the user application
ENV APPSODY_INSTALL= 

# Command to be executed in 'run' mode (change this to launch your application)
ENV APPSODY_RUN="/bin/bash /project/userapp/hello.sh"
# Command to be executed in 'run' mode  when re-launch it trigged (often the same as APPSODY_RUN)
ENV APPSODY_RUN_ON_CHANGE="/bin/bash /project/userapp/hello.sh"
#Signals whether to kill the server process before starting the ON_CHANGE action.
ENV APPSODY_RUN_KILL=false

# Command to be executed in 'debug' mode (change this to launch your application)
ENV APPSODY_DEBUG="echo -n \"Debugging \"; /bin/bash /project/userapp/hello.sh"
# Command to be executed in 'debug' mode when re-launch it trigged (often the same as APPSODY_DEBUG)
ENV APPSODY_DEBUG_ON_CHANGE="echo -n \"Debugging \"; /bin/bash /project/userapp/hello.sh"
# Signals whether to kill the server process before starting the ON_CHANGE action.
ENV APPSODY_DEBUG_KILL=false

# Command to be executed in 'run' mode (change this to launch your application)
ENV APPSODY_TEST="/bin/bash /project/userapp/tests/test.sh"
# Command to be executed in 'run' mode on when re-launch it trigged (often the same as APPSODY_TEST)
ENV APPSODY_TEST_ON_CHANGE="/bin/bash /project/userapp/tests/test.sh"
# Signals whether to kill the server process before starting the ON_CHANGE action.
ENV APPSODY_TEST_KILL=false

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config
WORKDIR /project

ENV PORT=8080
EXPOSE 8080
