name: Spring Boot® on Open Liberty
version: 0.1.11
description: Spring Boot on Open Liberty & OpenJ9 using Maven
license: Apache-2.0
language: java
maintainers:
 - name: Ozzy
   email: ozzy@ca.ibm.com
   github-id: bardweller
default-template: default
requirements:
   appsody-version: ">= 0.5.0"
templating-data:
  parentpomgroup: dev.appsody
  parentpomid: java-spring-boot2-liberty
  parentpomrange: '[0.1, 0.2)'