[package]
name = "appsody-rocket"
version = "0.1.0"
description = "Package containing dependencies for the Appsody Rocket stack"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
rocket_prometheus = "0.3.0"

[lib]
path = "src/lib.rs"
test = true