FROM kabanero/ubi8-maven:0.3.1


LABEL vendor="Kabanero" \
    name="kabanero/java-microprofile" \
    version="0.2.26" \
    summary="Image for Kabanero java-microprofile development" \
    description="This image is the Kabanero development container for the java-microprofile stack"

USER root

RUN groupadd java_group \
 && useradd --gid java_group --shell /bin/bash --create-home java_user \
 && mkdir -p /mvn/repository \
 && chown -R java_user:java_group /mvn

# Dependency install
COPY --chown=java_user:java_group ./LICENSE /licenses/
COPY --chown=java_user:java_group ./project /project
COPY --chown=java_user:java_group ./config /config

USER java_user

RUN  /project/util/check_version build

WORKDIR /project/
RUN mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository install dependency:go-offline -DskipTests
RUN mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository install dependency:go-offline -DskipTests -f pom-dev.xml

WORKDIR /project/user-app
RUN chown -R java_user:java_group /project
RUN chown -R java_user:java_group /config
RUN chown -R java_user:java_group /mvn
RUN chmod -R 0777 /mvn

ENV APPSODY_USER_RUN_AS_LOCAL=true

ENV APPSODY_MOUNTS=".:/project/user-app;~/.m2/repository:/mvn/repository"
ENV APPSODY_DEPS=

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/target
ENV APPSODY_WATCH_REGEX="^.*(.xml|.java|.properties)$"

ENV APPSODY_INSTALL="../validate.sh && mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository install -DskipTests && /project/install-dev-deps.sh"

ENV APPSODY_RUN="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository liberty:run"
ENV APPSODY_RUN_ON_CHANGE="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository package -DskipTests"
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository liberty:debug"
ENV APPSODY_DEBUG_ON_CHANGE="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository package -DskipTests"
ENV APPSODY_DEBUG_KILL=false

ENV APPSODY_TEST="mvn -B --no-transfer-progress -Dmaven.repo.local=/mvn/repository verify"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
