name: starter sample runnable stack
version: 0.1.0
description: starter sample stack that can be run by appsody, to help creation of more stacks
license: Apache-2.0
language: bash
maintainers: 
  - name: Henry Nash
    email: henry.nash@uk.ibm.com
    github-id: henrynash
default-template: simple