apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: APPSODY_PROJECT_NAME
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE 
  stack: APPSODY_STACK
  service:
    type: NodePort
    port: APPSODY_PORT
    annotations:
      prometheus.io/scrape: 'true'
  monitoring:
    labels:
      k8s-app: APPSODY_PROJECT_NAME
  readinessProbe:
    # By default, Kitura's liveness and readiness endpoints are the same.
    # You may wish to implement a custom readiness endpoint that is appropriate for
    # the initialization of your app - if so, adjust the route here.
    failureThreshold: 12
    httpGet:
      path: /health
      port: APPSODY_PORT
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: APPSODY_PORT
    initialDelaySeconds: 5
periodSeconds: 2
  expose: true
