FROM rust:1.37

RUN apt-get update && apt-get install -y lldb

ENV CARGO_HOME=/usr/local/cargo/deps

RUN useradd --gid 0 --create-home rust_user \
  && mkdir -p $CARGO_HOME \
  && chown -R rust_user:0 $CARGO_HOME

ENV APPSODY_PROJECT_DIR="/project"

ENV APPSODY_MOUNTS=.:/project/user-app
ENV APPSODY_DEPS=$CARGO_HOME

ENV APPSODY_WATCH_DIR="/project/user-app"
ENV APPSODY_WATCH_REGEX="^(Cargo.toml|.*.rs)$"

ENV APPSODY_RUN="cargo run"
ENV APPSODY_RUN_ON_CHANGE="cargo run"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_TEST="cargo test"

ENV APPSODY_DEBUG="cargo build && lldb-server platform --listen '*:1234' --min-gdbserver-port 5000 --max-gdbserver-port 5001 --server"
ENV APPSODY_DEBUG_ON_CHANGE="$APPSODY_DEBUG"
ENV APPSODY_DEBUG_KILL=true

COPY  ./LICENSE /licenses
COPY --chown=rust_user:0 ./project /project
COPY --chown=rust_user:0 ./config /config

WORKDIR /project/user-app

USER rust_user

ENV PORT=8000

EXPOSE 8000
EXPOSE 1234
EXPOSE 5000