FROM rust:1.37

ENV APPSODY_MOUNTS=.:/project/user-app
ENV APPSODY_DEPS=$CARGO_HOME/registry

ENV APPSODY_WATCH_DIR="/project/user-app"
ENV APPSODY_WATCH_REGEX="(^.*.rs$)"

ENV APPSODY_RUN="cargo run"
ENV APPSODY_RUN_ON_CHANGE="cargo run"
ENV APPSODY_RUN_KILL=false

ENV APPSODY_TEST="cargo test"

COPY ./LICENSE /licenses
COPY ./project /project
COPY ./config /config

WORKDIR /project/user-app

ENV PORT=8000

EXPOSE 8000