FROM registry.access.redhat.com/ubi8/nodejs-12:1-27

LABEL vendor="Kabanero" \
    name="kabanero/nodejs" \
    version="0.3.1" \
    summary="Image for Kabanero Nodejs development" \
    description="This image contains the Kabanero development stack for the Nodejs collection"

USER root
RUN yum install --disableplugin=subscription-manager python2 -y
RUN ln -s /usr/bin/python2 /usr/bin/python

ENV APPSODY_MOUNTS=/:/project/user-app
ENV APPSODY_DEPS=/project/user-app/node_modules

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/node_modules
ENV APPSODY_WATCH_REGEX="^.*.js$"

ENV APPSODY_PREP="npm install && npm audit fix"

ENV APPSODY_RUN="npm start --node-options --require=appmetrics-dash/attach"
ENV APPSODY_RUN_ON_CHANGE="npm start --node-options --require=appmetrics-dash/attach"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="npm start --node-options --inspect=0.0.0.0 --require=appmetrics-dash/attach"
ENV APPSODY_DEBUG_ON_CHANGE="npm start --node-options --inspect=0.0.0.0 --require=appmetrics-dash/attach"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="npm test"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

RUN chown -R default:root /project
WORKDIR /project
USER default
RUN mkdir -p /project/user-app/node_modules
RUN npm install

WORKDIR /project/user-app

ENV PORT=3000

EXPOSE 3000
EXPOSE 9229
