FROM node:12
  
RUN useradd -m node_user && groupadd node_group

ENV APPSODY_MOUNTS=/:/project/user-app
ENV APPSODY_DEPS=/project/user-app/node_modules
ENV APPSODY_PROJECT_DIR=/project
ENV APPSODY_USER_RUN_AS_LOCAL=true

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/node_modules;/project/user-app/.config
ENV APPSODY_WATCH_REGEX="^.*.js$"

ENV APPSODY_PREP="npm install && npm audit fix"

ENV APPSODY_RUN="npm start --node-options --require=appmetrics-dash/attach"
ENV APPSODY_RUN_ON_CHANGE="npm start --node-options --require=appmetrics-dash/attach"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="npm start --node-options --inspect=0.0.0.0 --require=appmetrics-dash/attach"
ENV APPSODY_DEBUG_ON_CHANGE="npm start --node-options --inspect=0.0.0.0 --require=appmetrics-dash/attach"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="npm test"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

COPY --chown=node_user:node_group ./LICENSE /licenses/
COPY --chown=node_user:node_group ./project /project
COPY --chown=node_user:node_group ./config /config

WORKDIR /project
USER node_user

RUN mkdir -p /project/user-app/node_modules
RUN npm install && npm audit fix

WORKDIR /project/user-app
ENV NODE_PATH=/project/user-app/node_modules
ENV NPM_CONFIG_CACHE=/project/user-app/.npm
ENV XDG_CONFIG_HOME=/project/user-app/.config

ENV PORT=3000

EXPOSE 3000
EXPOSE 9229
