name: Quarkus
version: 0.1.3
description: Quarkus runtime for running Java applications
license: Apache-2.0
language: java
maintainers:
  - name: Paul Robinson
    email: probinso@redhat.com
    github-id: paulrobinson
default-template: default