name: Quarkus
version: 0.1.1
description: Quarkus runtime for running Java applications
license: Apache-2.0
maintainers:
  - name: Paul Robinson
    email: probinso@redhat.com
    github-id: paulrobinson
default-template: default