FROM golang:1

ENV APPSODY_MOUNTS=/:/project/user-app

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/vendor
ENV APPSODY_WATCH_REGEX="^.*.(go|toml)$"

ENV APPSODY_PREP="bash /vendor.sh"

ENV APPSODY_RUN="go run ."
ENV APPSODY_RUN_ON_CHANGE="go run ."
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG="dlv debug --listen 0.0.0.0:9229 --headless ."
ENV APPSODY_DEBUG_ON_CHANGE="dlv debug --listen 0.0.0.0:9229 --headless ."
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="go test ."
ENV APPSODY_TEST_KILL=false

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config
COPY ./vendor.sh /vendor.sh

RUN chmod +x /vendor.sh

WORKDIR /project/user-app

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u github.com/go-delve/delve/cmd/dlv

ENV PORT=3000

EXPOSE 3000
EXPOSE 9229

