name: Rust
version: 0.3.0
description: Runtime for Rust applications
license: Apache-2.0
language: rust
maintainers:
  - name: Sandy Koh
    email: sandy.koh@ibm.com
    github-id: skoh7645
  - name: Enrique Lacal
    email: enrique.lacal.bereslawski@ibm.com
    github-id: EnriqueL8
default-template: simple