name: Node.js
version: 0.2.2
description: Runtime for Node.js applications
license: Apache-2.0
maintainers:
  - name: Chris Bailey
    email: cnbailey@gmail.com
    github-id: seabaylea
  - name: Neeraj Laad
    email: neeraj.laad@gmail.com
    github-id: neeraj-laad
default-template: simple