# Dockerfile for building the stack
FROM quay.io/quarkus/centos-quarkus-maven:19.2.1

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

WORKDIR /project

RUN mvn -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B install dependency:go-offline -DskipTests

ENV APPSODY_MOUNTS=".:/project/user-app"
ENV APPSODY_DEPS="/home/quarkus/.m2"

ENV APPSODY_RUN="./mvnw -B compile quarkus:dev"
ENV APPSODY_RUN_ON_CHANGE=""
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG="./mvnw -B -Ddebug compile quarkus:dev"
ENV APPSODY_DEBUG_ON_CHANGE=""
ENV APPSODY_DEBUG_KILL=false

ENV APPSODY_TEST="./mvnw -B test"
ENV APPSODY_TEST_ON_CHANGE="./mvnw -B test"
ENV APPSODY_TEST_KILL=true

WORKDIR /project/user-app

ENV PORT=8080

EXPOSE 8080
EXPOSE 5005
