# Dockerfile for building the stack
FROM quay.io/quarkus/centos-quarkus-maven:19.1.1

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

WORKDIR /project

RUN mvn install dependency:go-offline -DskipTests

ENV APPSODY_USER_RUN_AS_LOCAL=true

ENV APPSODY_MOUNTS=".:/project/user-app/;~/.m2/repository:/home/$(id -un)/.m2/repository"
ENV APPSODY_DEPS=

ENV APPSODY_RUN="./mvnw compile quarkus:dev"
ENV APPSODY_RUN_ON_CHANGE=""
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG="./mvnw -Ddebug compile quarkus:dev"
ENV APPSODY_DEBUG_ON_CHANGE=""
ENV APPSODY_DEBUG_KILL=false

ENV APPSODY_TEST="./mvnw test"
ENV APPSODY_TEST_ON_CHANGE="./mvnw test"
ENV APPSODY_TEST_KILL=true

WORKDIR /project/user-app

ENV PORT=8080

EXPOSE 8080
EXPOSE 5005
