name: Node.js Functions
version: 0.1.0
description: Serverless runtime for Node.js functions
license: Apache-2.0
maintainers:
  - name: Chris Bailey
    email: cnbailey@gmail.com
    github-id: seabaylea
default-template: simple