name: Node.js Functions
version: 0.2.1
description: Serverless runtime for Node.js functions
license: Apache-2.0
language: nodejs
maintainers:
  - name: Chris Bailey
    email: cnbailey@gmail.com
    github-id: seabaylea
  - name: Gireesh Punathil
    email: gpunathi@in.ibm.com
    github-id: gireeshpunathil
default-template: simple
requirements:
  appsody-version: ">= 0.2.7"
