id: nodejs-functions
name: Node.js Functions application
version: 0.1.0
description: Simple Node.js Functions application with health checks and application metrics for Prometheus.
maintainer: Chris Bailey <cnbailey@gmail.com>
default-template: simple
license: Apache-2.0
