id: nodejs-express
name: Node.js Express application
version: 0.2.0
description: Simple Node.js Express application with health checks and aplicaiton metrics for Prometheus.
maintainer: Neeraj Laad <neeraj.laad@gmail.com>
default-template: simple
license: Apache-2.0