name: Node.js Express
version: 0.4.0
description: Express web framework for Node.js
license: Apache-2.0
language: nodejs
maintainers:
  - name: Sam Roberts
    email: vieuxtech@gmail.com
    github-id: sam-github
default-template: simple
