apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-src-{{.nameSuffix}}
  namespace: {{.namespace}}
spec:
  params:
  - name: url
    value: {{.tag.fromRegistry}}
  type: image
