name: Swift
version: 0.1.1
description: Runtime for Swift applications
license: Apache-2.0
maintainers:
  - name: Ian Partridge
    email: i.partridge@uk.ibm.com
    github-id: ianpartridge
default-template: simple