name: Swift
version: 0.2.4
description: Appsody runtime for Swift applications
license: Apache-2.0
language: swift
maintainers:
  - name: Ian Partridge
    email: i.partridge@uk.ibm.com
    github-id: ianpartridge
  - name: David Jones
    email: djones6@uk.ibm.com
    github-id: djones6
default-template: simple
requirements:
  appsody-version: ">= 0.2.7"
