FROM python:3.7

RUN pip install --user pipenv
ENV PATH=/root/.local/bin:$PATH

ENV APPSODY_MOUNTS=/:/project/userapp
ENV APPSODY_DEPS=/project/deps

ENV APPSODY_WATCH_DIR=/project/userapp
ENV APPSODY_WATCH_IGNORE_DIR=/project/userapp/dependencies
ENV APPSODY_WATCH_REGEX="^.*.py$"

ENV APPSODY_INSTALL="cd /project/userapp;pipenv lock -r > requirements.txt;python -m pip install -r requirements.txt -t /project/deps;python -m pip install ptvsd -t /project/deps;cp -rf /project/deps/* /project/userapp/dependencies"

ENV APPSODY_RUN="python -m flask run --host=0.0.0.0 --port=8080"
ENV APPSODY_RUN_ON_CHANGE="python -m flask run --host=0.0.0.0 --port=8080"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="python -m ptvsd --host 0.0.0.0 --port 5678 -m flask run --host=0.0.0.0 --port=8080"
ENV APPSODY_DEBUG_ON_CHANGE="python -m ptvsd --host 0.0.0.0 --port 5678 -m flask run --host=0.0.0.0 --port=8080"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="python -m unittest discover -s tests -p "*.py"'"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

COPY ./project /project
WORKDIR /project
RUN pipenv install
RUN pipenv lock -r > requirements.txt
RUN python -m pip install -r requirements.txt -t /project/deps

ENV PORT=8080
ENV PYTHONPATH=/project/deps
ENV FLASK_APP=/project/server/__init__.py

EXPOSE 8080
EXPOSE 5678
