apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: APPSODY_PROJECT_NAME
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE 
  stack: APPSODY_STACK
  service:
    type: NodePort
    port: APPSODY_PORT
  expose: true
