id: kotlin-spring-boot2
name: Kotlin application using Spring Boot 2
version: 0.1.0
description: Spring Boot 2 project with health and metrics actuators enabled. Metrics support is provided by Micrometer, and is configured with Prometheus support.
maintainer: Pushkar N Kulkarni<pushkar.nk@in.ibm.com>
default-template: default
license: Apache-2.0
