apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata: 
  name: APPSODY_PROJECT_NAME
spec:
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE
  stack: rust
  service:
    type: NodePort
    port: APPSODY_PORT
  expose: true