FROM adoptopenjdk/openjdk8-openj9
USER root
RUN  apt-get -qq update \
  && apt-get -qq install -y curl maven xmlstarlet wget \
  && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y \
  && apt-get -qq clean \
  && rm -rf /tmp/* /var/lib/apt/lists/*

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

RUN  /project/util/check_version build

WORKDIR /project/
RUN mkdir -p /mvn/repository
RUN mvn -B -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B -Pstack-image-package -Dmaven.repo.local=/mvn/repository liberty:install-server liberty:create install dependency:go-offline
RUN chmod -R 777 /opt/ol


WORKDIR /project/user-app

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;.:/project/user-app"

ENV APPSODY_USER_RUN_AS_LOCAL=true

# Allow validate to distinguish build via APPSODY_DEV_MODE
ENV APPSODY_PREP="/project/run-stack.sh prep"

ENV APPSODY_RUN="/project/run-stack.sh run"

ENV APPSODY_DEBUG="/project/run-stack.sh debug"

ENV APPSODY_TEST="/project/run-stack.sh test"

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
