FROM kabanero/ubi8-maven:0.3.1
RUN useradd --gid 0 --shell /bin/bash --create-home java_user \
  && mkdir -p /mvn/repository \
  && chown -R java_user:0 /mvn \
  && mkdir -p /opt/ol \
  && chown -R java_user:0 /opt

COPY ./LICENSE /licenses/
COPY --chown=java_user:0 ./project /project
COPY --chown=java_user:0 ./config /config

USER java_user

RUN  /project/util/check_version build

WORKDIR /project/

RUN mkdir -p /mvn/repository
RUN mvn -B -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B -Pstack-image-package -Dmaven.repo.local=/mvn/repository liberty:install-server install dependency:go-offline

WORKDIR /project/user-app

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;.:/project/user-app"

ENV APPSODY_USER_RUN_AS_LOCAL=true

# Allow validate to distinguish build via APPSODY_DEV_MODE
ENV APPSODY_PREP="/project/run-stack.sh prep"

ENV APPSODY_RUN="/project/run-stack.sh run"

ENV APPSODY_DEBUG="/project/run-stack.sh debug"

ENV APPSODY_TEST="/project/run-stack.sh test"

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
