FROM adoptopenjdk/openjdk8-openj9

USER root
RUN  apt-get -qq update \
  && apt-get -qq install -y curl maven xmlstarlet wget \
  && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y \
  && apt-get -qq clean \
  && rm -rf /tmp/* /var/lib/apt/lists/*

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config /config

RUN  /project/util/check_version build

WORKDIR /project/
RUN mkdir -p /mvn/repository
RUN mvn -B -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B -Pdev -Dmaven.repo.local=/mvn/repository liberty:install-server install dependency:go-offline

WORKDIR /project/user-app
RUN /project/install-dev-deps.sh

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;.:/project/user-app"
ENV APPSODY_DEPS=

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/target

# Work around v3.1 issues with dev mode reacting to pom.xml change but should eventually not require this.
ENV APPSODY_WATCH_REGEX="^.*(.xml)$"

ENV APPSODY_USER_RUN_AS_LOCAL=true

# Set APPSODY_DEV_MODE to get in the habit in case we need it someday
ENV APPSODY_PREP="export APPSODY_DEV_MODE=prep;  ../validate.sh"

ENV APPSODY_RUN="export APPSODY_DEV_MODE=run JVM_ARGS='-javaagent:resources/javametrics-agent.jar'; mvn -B -Dmaven.repo.local=/mvn/repository liberty:dev"
# See ENV APPSODY_WATCH_REGEX comment
ENV APPSODY_RUN_ON_CHANGE="export APPSODY_DEV_MODE=run JVM_ARGS='-javaagent:resources/javametrics-agent.jar'; ../validate.sh && mvn -Dmaven.repo.local=/mvn/repository liberty:dev"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="export APPSODY_DEV_MODE=debug JVM_ARGS='-javaagent:resources/javametrics-agent.jar'; mvn -B -Dmaven.repo.local=/mvn/repository liberty:dev"
# See ENV APPSODY_WATCH_REGEX comment
ENV APPSODY_DEBUG_ON_CHANGE="export APPSODY_DEV_MODE=debug JVM_ARGS='-javaagent:resources/javametrics-agent.jar'; ../validate.sh && mvn -Dmaven.repo.local=/mvn/repository liberty:dev"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="export APPSODY_DEV_MODE=test JVM_ARGS='-javaagent:resources/javametrics-agent.jar'; mvn -B -Dmaven.repo.local=/mvn/repository liberty:dev"
# See ENV APPSODY_WATCH_REGEX comment
ENV APPSODY_TEST_ON_CHANGE="export APPSODY_DEV_MODE=test JVM_ARGS='-javaagent:resources/javametrics-agent.jar'; ../validate.sh && mvn -Dmaven.repo.local=/mvn/repository liberty:dev"
ENV APPSODY_TEST_KILL=true


ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
