FROM swift:5.0

RUN apt-get update \
 && apt-get install -y zlib1g-dev libcurl4-openssl-dev libssl-dev \
 && apt-get clean \
 && echo 'Finished installing dependencies'

ENV APPSODY_MOUNTS=/:/project/user-app
ENV APPSODY_DEPS=/project/user-app/.build

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/.build
ENV APPSODY_WATCH_REGEX="^.*.swift$"

ENV APPSODY_INSTALL="swift build"

ENV APPSODY_RUN="swift run"
ENV APPSODY_RUN_ON_CHANGE="swift run"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG=""
ENV APPSODY_DEBUG_ON_CHANGE=""
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="swift test"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

COPY ./project /project
WORKDIR /project/user-app

ENV PORT=8080

EXPOSE 8080
