#Kabanero! on activate substitute CollectionName for text '${collection-name}'
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: ${collection-name}-build-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: pathToDockerFile
        default: /workspace/extracted/Dockerfile
      - name: pathToContext
        default: /workspace/extracted
  outputs:
    resources:
      - name: docker-image
        type: image
  steps:
    - name: assemble-extract-step
      securityContext:
        privileged: true
      image: appsody/appsody-docker
      command: ["/bin/bash"]
      args:
        - -c
        - "/setupAndRunExtract.sh"
      env:
        - name: gitsource
          value: git-source
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: build-push-step
      env:
      - name: DOCKER_CONFIG
        value: /builder/home/.docker
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.docker-image.url}
        - --context=${inputs.params.pathToContext}
        - --skip-tls-verify
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
