#Kabanero! on activate substitute CollectionId for text 'CollectionId'
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: CollectionId-deploy-task
spec:
  inputs:
    resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
    params:
    - name: repository-name
      default: CollectionId
    - name: app-deploy-file-name
      default: app-deploy.yaml
  steps:
  - name: modify-app-deploy-yaml
    image: registry.access.redhat.com/ubi8/ubi:8.1-277
    command: ['/bin/bash']
    args:
    - -ce
    - |
      echo "Checking for app-deploy.yaml"
      APP_DEPLOY_YAML=$(find /workspace/git-source -name ${YAMLFILE} -type f)
      if [ -z "$APP_DEPLOY_YAML" ]; then
        echo "ERROR: app-deploy.yaml not found in your project after the build task ran which should have generated it.  Please verify before running the pipeline."
        exit 1
      fi
    env:
    - name: REPO
      value: $(inputs.params.repository-name)
    - name: IMG
      value: $(inputs.resources.docker-image.url)
    - name: YAMLFILE
      value: $(inputs.params.app-deploy-file-name)
  - name: deploy-image
    image: kabanero/kabanero-utils:0.3.0
    command: ['/bin/sh']
    args: ['-c', 'find /workspace/git-source -name ${YAMLFILE} -type f|xargs kubectl apply -f']
    env:
    - name: YAMLFILE
      value: $(inputs.params.app-deploy-file-name)