#Kabanero! on activate substitute CollectionId for text 'CollectionId'
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: CollectionId-image-retag-task
spec:
  inputs:
    resources:
      - name: docker-src-image
        type: image
      - name: docker-dest-image
        type: image
    params:
      - name: pathToDockerFile
        default: /workspace/extracted/Dockerfile
      - name: pathToContext
        default: /workspace/extracted
  outputs:
    resources:
      - name: docker-dest-image
        type: image
  steps:
    - name: buildah-pull
      securityContext:
        privileged: true
      image: appsody/appsody-buildah:0.5.0-buildah1.9.0
      command: ['buildah', 'pull', '--tls-verify=false', '$(inputs.resources.docker-src-image.url)']
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - name: buildah-tag
      securityContext:
        privileged: true
      image: appsody/appsody-buildah:0.5.0-buildah1.9.0
      command: ['buildah', 'tag', '$(inputs.resources.docker-src-image.url)', '$(inputs.resources.docker-dest-image.url)']
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - name: buildah-push
      securityContext:
        privileged: true
      image: appsody/appsody-buildah:0.5.0-buildah1.9.0
      command: ['buildah', 'push', '--tls-verify=false', '$(outputs.resources.docker-dest-image.url)', 'docker://$(outputs.resources.docker-dest-image.url)']
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
