FROM openjdk8-openj9-local

USER root
RUN  apt-get -qq update \
  && apt-get -qq install -y curl maven \
  && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y \
  && apt-get -qq clean \
  && rm -rf /tmp/* /var/lib/apt/lists/*

COPY ./config /config
COPY ./project /project
WORKDIR /project/

RUN mvn install dependency:go-offline -DskipTests -f pom-dev.xml

WORKDIR /project/user-app

ENV APPSODY_MOUNTS="~/.m2/repository:/root/.m2/repository;.:/project/user-app"
ENV APPSODY_DEPS=

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/target
ENV APPSODY_WATCH_REGEX="(pom.xml)$"

ENV APPSODY_INSTALL="../validate.sh && mvn install -DskipTests && /project/install-dev-deps.sh"

ENV APPSODY_RUN="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn liberty:dev -DskipTests"
ENV APPSODY_RUN_ON_CHANGE="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn liberty:dev -DskipTests"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn liberty:dev -Dliberty.debug.port=7777"
ENV APPSODY_DEBUG_ON_CHANGE="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn liberty:dev -Dliberty.debug.port=7777"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="JVM_ARGS='-javaagent:resources/javametrics-agent.jar' mvn verify"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
