FROM adoptopenjdk/openjdk8-openj9

USER root
RUN  apt-get -qq update \
  && apt-get -qq install -y curl maven \
  && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y \
  && apt-get -qq clean \
  && rm -rf /tmp/* /var/lib/apt/lists/*

COPY ./config /config
COPY ./project /project

WORKDIR /project/
RUN mkdir -p /mvn/repository
RUN mvn -B -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B -Dmaven.repo.local=/mvn/repository install dependency:go-offline -DskipTests
RUN mvn -Dmaven.repo.local=/mvn/repository install dependency:go-offline -DskipTests -f pom-dev.xml

WORKDIR /project/user-app

ENV APPSODY_MOUNTS="~/.m2/repository:/root/.m2/repository;src:/project/user-app/src;pom.xml:/project/user-app/pom.xml"
ENV APPSODY_DEPS=/project/user-app/target

ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/target
ENV APPSODY_WATCH_REGEX="(pom.xml)$"

ENV APPSODY_INSTALL="../validate.sh && mvn install -DskipTests && /project/install-dev-deps.sh"

ENV APPSODY_RUN="mvn liberty:dev -DskipTests"
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG="mvn liberty:dev -Dliberty.debug.port=7777"
ENV APPSODY_DEBUG_KILL=false

ENV APPSODY_TEST="mvn verify"
ENV APPSODY_TEST_ON_CHANGE=""
ENV APPSODY_TEST_KILL=false

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
