name: Rocket
version: 0.1.0 
description: Rocket web framework for Rust 
license: Apache-2.0
language: rust
maintainers:
  - name: Sandy Koh
    email: sandy.koh@ibm.com
    github-id: skoh7645
default-template: simple