version: '2'
services:
  index:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    image: "appsody/appsody-index"
    container_name: "appsody-index"
    ports:
      - "8008:8080"
      - "8003:8443"
    environment:
      - EXTERNAL_URL=http://localhost:8008/

  verify:
    image: "appsody/appsody-index"
    container_name: "appsody-verify"
    entrypoint: ""
    command: sh -c "/opt/startup.sh; cat /opt/www/public/*.yaml; ls /opt/www/public"
    environment:
      - EXTERNAL_URL=https://localhost:8003/
      - DRY_RUN=true
