name: Python Flask
version: 0.1.4
description: Flask web Framework for Python
language: python
maintainers:
  - name: Chris Bailey
    email: cnbailey@gmail.com
    github-id: seabaylea
  - name: Henry Nash
    email: henry.nash@uk.ibm.com
    github-id: henrynash
default-template: simple
license: Apache-2.0
