name: Python Flask
version: 0.2.1
description: Flask web Framework for Python
language: python
maintainers:
  - name: Chris Bailey
    email: cnbailey@gmail.com
    github-id: seabaylea
  - name: Henry Nash
    email: henry.nash@uk.ibm.com
    github-id: henrynash
default-template: simple
license: Apache-2.0
requirements:
  appsody-version: ">= 0.2.7"
  docker-version: ">= 17.09.0"
