#!/bin/bash
# This is a small utility script that uses OSGi VersionRange and Version
# classes to verify whether or not a specified version matches is contained
# within a specified range.
#
cd "$( dirname "${BASH_SOURCE[0]}" )"

if [ $# -lt 1 ]; then
    ACTION=range
else
    ACTION=$1
    shift
fi

range_check() {
    java -cp .:org.osgi.core-6.0.0.jar RangeIncludesVersion "$1" "$2"
    return $?
}

sniff() {
    range_check "$1" "$2"
    if [ $? -ne $3 ]; then
        echo "Test |'$1' contains '$2'| should return $3. Got $?"
        exit 1
    fi
}

case "$ACTION" in
  build)
    wget -q https://repo1.maven.org/maven2/org/osgi/org.osgi.core/6.0.0/org.osgi.core-6.0.0.jar
    javac -cp org.osgi.core-6.0.0.jar *.java

    sniff "[0.3,0.4)" "0.3.7" 0
    sniff "[0.3,0.4)" "0.4" 1
    sniff "[0.3,0.4)" "0.2" 1
    exit 0
  ;;
  contains)
    if [ $# -lt 2 ]; then
        echo "Specify version information: check_version contains <range_spec> <version>"
        exit 1
    fi

    range_check "$1" "$2"
    exit $?
  ;;
esac

