apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name:  {{.nameSuffix}}
  namespace: {{.namespace}}
spec:
  pipelineRef:
    name: {{.collectionID}}-build-pipeline
  resources:
  - name: git-source
    resourceRef:
      name: git-{{.nameSuffix}}
  serviceAccount: {{.serviceAccount}}
  timeout: {{.timeout}}
