name: Eclipse Vert.x
version: 0.1.5
description: Eclipse Vert.x runtime for running Java applications
license: EPL-2.0
language: java
maintainers:
  - name: Erik Jan de Wit
    email: edewit@redhat.com
    github-id: edewit
default-template: default
