name: Eclipse MicroProfile®
version: 0.2.3
description: Eclipse MicroProfile using OpenJ9 and Maven
license: Apache-2.0
maintainers:
  - name: Emily Jiang
    email: emijiang6@googlemail.com
    github-id: Emily-Jiang
  - name: Neeraj Laad
    email: neeraj.laad@gmail.com
    github-id: neeraj-laad
default-template: default