name: Eclipse MicroProfile®
version: 0.2.11
description: Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
license: Apache-2.0
language: java
maintainers:
  - name: Emily Jiang
    email: emijiang6@googlemail.com
    github-id: Emily-Jiang
  - name: Neeraj Laad
    email: neeraj.laad@gmail.com
    github-id: neeraj-laad
default-template: default
