[package]
name = "rust-simple"
version = "0.1.0"
authors = ["Name <name@email.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-simple"
path = "src/main.rs"