FROM node:12
  
RUN useradd -m node_user && groupadd node_group

ENV APPSODY_MOUNTS=/:/project/user-app
ENV APPSODY_DEPS=/project/user-app/node_modules
ENV APPSODY_USER_RUN_AS_LOCAL=true

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/node_modules
ENV APPSODY_WATCH_REGEX="^.*.json$"

ENV APPSODY_PREP="npm install --prefix user-app && npm audit fix --prefix user-app"

ENV APPSODY_RUN="npm start"
ENV APPSODY_RUN_ON_CHANGE="npm start"
ENV APPSODY_RUN_KILL=true

ENV APPSODY_DEBUG="npm run debug"
ENV APPSODY_DEBUG_ON_CHANGE="npm run debug"
ENV APPSODY_DEBUG_KILL=true

ENV APPSODY_TEST="npm test"

COPY --chown=node_user:node_group ./LICENSE /licenses/
COPY --chown=node_user:node_group ./project /project
COPY --chown=node_user:node_group ./config /config

WORKDIR /project
USER node_user

RUN mkdir -p /project/user-app/node_modules
RUN npm install && npm audit fix

ENV PORT=3000
ENV NODE_PATH=/project/user-app/node_modules
ENV NPM_CONFIG_CACHE=/project/user-app/.npm

EXPOSE 3000
EXPOSE 9229